# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0052_auto_20151128_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approve_reason',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
