# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0053_application_approve_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialaccount',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='pic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialaccount',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
