# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0055_auto_20170101_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialaccount',
            name='pic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
